- hosts: all
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        update_cache: yes
        state: latest
