- hosts: all
  become: true
  user: ubuntu
  become: true
  gather_facts: false
  
- tasks:
    - name: Install Apache
      apt: 
        name: apache2
        update_cache: yes
        state: latest